// Re-export all types from the goatcounter module
export type {
  CountTotalResponse,
  GoatCounterAuthResult,
  GoatCounterPath,
  GoatCounterUser,
  HitList,
  HitListStat,
  HitsResponse,
  HitStat,
  PathsResponse,
  RefsResponse,
  Site,
  SiteSettings,
  SitesResponse,
  StatsPage,
  StatsDetailPage,
  StatsResponse,
  UserSettings,
} from "$lib/server/goatcounter/types.js";
