apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: default-security-headers
  labels:
    app: gtcd
spec:
  headers:
    stsSeconds: 31536000
    stsIncludeSubdomains: true
    contentTypeNosniff: true
    browserXssFilter: true
    referrerPolicy: strict-origin-when-cross-origin
    customResponseHeaders:
      X-Frame-Options: DENY
      Permissions-Policy: camera=(), microphone=(), geolocation=()
