apiVersion: v1
kind: Secret
metadata:
  name: gtcd-env
type: Opaque
stringData:
  DOMAIN: ${DOMAIN}
  GOATCOUNTER_URL: ${GOATCOUNTER_URL}
  GOATCOUNTER_API_KEY: ${GOATCOUNTER_API_KEY}
  SESSION_SECRET: ${SESSION_SECRET}
  REDIS_URL: ${REDIS_URL}
